// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX3gvbDFdswY18C2MoitYhyY6WNks9xqQ',
    appId: '1:488589250027:web:18900ce944e3289603ddae',
    messagingSenderId: '488589250027',
    projectId: 'todo-app-sun-c9-137e4',
    authDomain: 'todo-app-sun-c9-137e4.firebaseapp.com',
    storageBucket: 'todo-app-sun-c9-137e4.appspot.com',
    measurementId: 'G-GKB2KWJ4V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa49pxTwBml2hEmbTvrBkhnnnVZXP6ubY',
    appId: '1:488589250027:android:79e4b77747f244b703ddae',
    messagingSenderId: '488589250027',
    projectId: 'todo-app-sun-c9-137e4',
    storageBucket: 'todo-app-sun-c9-137e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2xiKQlLyghgoqdWhlnBczPUU0B_aH3yI',
    appId: '1:488589250027:ios:39e91003353fb98003ddae',
    messagingSenderId: '488589250027',
    projectId: 'todo-app-sun-c9-137e4',
    storageBucket: 'todo-app-sun-c9-137e4.appspot.com',
    iosBundleId: 'com.example.todoAppC9Sun4pm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2xiKQlLyghgoqdWhlnBczPUU0B_aH3yI',
    appId: '1:488589250027:ios:0d9fd3cfd7d777ae03ddae',
    messagingSenderId: '488589250027',
    projectId: 'todo-app-sun-c9-137e4',
    storageBucket: 'todo-app-sun-c9-137e4.appspot.com',
    iosBundleId: 'com.example.todoAppC9Sun4pm.RunnerTests',
  );
}